import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth pages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <body
      >
        <h1>I come from the parent (auth) layout, even though (auth) is not in the route path!</h1>
        {children}
      </body>
  );
}
