/// !!! IMPORTANT !!!
// IF WE ARE USING MULTIPLE ROUTE GROUPS WITHOUT AN EXTERNAL, SOLE "/" ROUTE

// THERE HAS TO BE A TOP LEVEL PAGE.TSX FILE IN ONLY ONE FO THE ROUTE GROUPS!!!
// THIS WILL BE THE ONLY "/" ROUTE - OTHERWISE, CONFLICT ERRORS WILL ARISE

import { Metadata } from "next";
import Link from "next/link";
import DelayedComponent from "./DelayedComponent";

// metadata can also be set (by exporting) in the page
// the metadata objects will merge, where the properties in the page will take priority over
// the ones in the layout
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
// check (routing-tutorial)/products/[productId] for dynamic metadata


export default function Home() {
    
    return (
        <>
            <h1>Home</h1>
            <ul>
                <li className="hover:underline">
                    <Link href={"/products/1"}>Product 1 no replace</Link>
                </li>
                <li className="hover:underline">
                    <Link href={"/products/2"}>Product 2 no replace</Link>
                </li>
                <li className="hover:underline">
                    <Link href={"/products/3"} replace>
                        Product 3 WITH replace
                    </Link>
                </li>
            </ul>
            <DelayedComponent />
        </>
    );
}
